### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by OmerMark** [cake808/Modbus-Flooding-Demo#1]
Hello Kevin,

I am a final-year student of Communication Systems Engineering, and I am working on my Bachelor’s final project, "Detecting Cyber Attacks on OT" (using Snort and Yara rules). While researching, I found your repo "Modbus Flooding Demo," which could help me a lot and save time so I can focus on detection.

Could I ask for the original code of the "Modbus/modbus-server" file before compilation?

Thanks a lot,

Omer

**Comment by kevincali** [comment]
Hey Omer,
unfortunately I didn't implement the `modbus-server` myself. I was only supplied the binary without any source code.

I wish you great success with your bachelor's project =)
